#!/bin/sh
chown root:wheel /System/Library/LaunchDaemons/com.unlimapps.uaunboxdlaunch.plist
chmod 644 /System/Library/LaunchDaemons/com.unlimapps.uaunboxdlaunch.plist

chmod 4755 /usr/libexec/uaunbox
chown root:wheel /usr/libexec/uaunbox

launchctl load /System/Library/LaunchDaemons/com.unlimapps.uaunboxdlaunch.plist
exit 0