#!/bin/sh
chown root:wheel /Library/LaunchDaemons/com.unlimapps.uaunboxdlaunch.plist
chmod 644 /Library/LaunchDaemons/com.unlimapps.uaunboxdlaunch.plist

chmod 4755 /usr/libexec/uaunbox
chown root:wheel /usr/libexec/uaunbox

launchctl load /Library/LaunchDaemons/com.unlimapps.uaunboxdlaunch.plist
exit 0